# Generated by Django 2.2.7 on 2019-11-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('spam', models.BooleanField(default=False)),
            ],
        ),
    ]
